### ISSUE TITLE
Azure Data Explorer In-A-Day Badge 

### ISSUE THREAD

**Issue by AnisNaim** [Azure/ADX-in-a-Day#10]
Hello 
Sorry to bother i have finished sending the 2 forms with the KQL queries one day ago. 
Can someone tell me when i will get this badge ?
Thank you so much
Have a nice WE

**Comment by allandecastro** [comment]
Hello
Same problem/question here :)

**Comment by AnisNaim** [comment]
> Hello Sorry to bother i have finished sending the 2 forms with the KQL queries one day ago. Can someone tell me when i will get this badge ? Thank you so much Have a nice WE

i havce received it few days after. Thank you :-)

**Comment by allandecastro** [comment]
Oh, still not received :/

@SuryaTejJosyula, any news about it?

**Comment by SuryaTejJosyula** [comment]
@allandecastro I will check if all answers have been submitted properly and Issue it asap.

**Comment by allandecastro** [comment]
I just received an email with the badge :)
I assume you found my answer so! Thanks 💯
