### ISSUE TITLE
ADX-In-A-Day completion digital badge not receievd

### ISSUE THREAD

**Issue by kuldeepsingh-in** [Azure/ADX-in-a-Day#14]
I submitted the KQL queries in the mentioned answer sheet. Neither I received a digital badge not I heard anything back about if something is wrong about my answers. Can someone please confirm if I'm missing something here?

**Comment by SuryaTejJosyula** [comment]
Hi Kuldeep, did you submit Lab 2 answers as well?  Can you let us know when did you submit lab 2 answers?

**Comment by SuryaTejJosyula** [comment]
Submitting answers to challenges in each of the 2 labs is necessary to earn the badge. Please submit Lab 2 as well.
