### ISSUE TITLE
improve accessibility | contrast of charm

### ISSUE THREAD

**Issue by ingebeumer** [Azure/ADX-in-a-Day#15]
Hello,
 
Please consider improving accessibility of ADX-in-a-Day by choosing a charm (in questions that require an answer) that has better contrast when using a darker theme in GitHub.

Appearance dark dimmed:
![image](https://github.com/Azure/ADX-in-a-Day/assets/40343254/216b8ff7-3a0a-446e-832b-ee26d84db863)
Appearance dark default:
![image](https://github.com/Azure/ADX-in-a-Day/assets/40343254/2940c25c-7c47-472a-9691-ea6919d1bf6e)
Appearance light default:
![image](https://github.com/Azure/ADX-in-a-Day/assets/40343254/27260feb-d140-44d1-87e5-4887f4b6d572)

**Comment by hfleitas** [comment]
@ingebeumer Thank you! 
We're considering these instead. Do you have a preference? We appreciate your feedback towards improving the accessibility. 
1. `:dart:`  🎯 
2. `:trophy:` 🏆 
3. `:white_check_mark:` ✅ 

+ @guregini

**Comment by ingebeumer** [comment]
@hfleitas, although I'm not an accessibility SME I prefer option 3 the checkmark. They are tasks you need to complete to earn the badge so the checkmark makes most sense to me and it's a charm that gets your attention. 
Dark dimmed:
![image](https://github.com/Azure/ADX-in-a-Day/assets/40343254/4e664fea-ef5b-4170-92f9-4708bd798045)
Light default:
![image](https://github.com/Azure/ADX-in-a-Day/assets/40343254/3994e3cd-4121-4c65-90b8-df648aa4ddbf)
Dark default:
![image](https://github.com/Azure/ADX-in-a-Day/assets/40343254/c2d9701a-25ff-4507-b2a9-211cd6cd8b9c)

**Comment by hfleitas** [comment]
Confirmed with our accessibility SME to use the ✅ 

Main repo fixed ✅
Lab 1 repo fixed ✅
Lab 2 repo fixed ✅
Quiz 1 fixed ✅
Quiz 2 fixed ✅

Thank you

**Comment by ingebeumer** [comment]
Looks great @hfleitas, I much appreciate the improvement.
