### ISSUE TITLE
Digital Badge not issued

### ISSUE THREAD

**Issue by Georgios-Grigoriou** [Azure/ADX-in-a-Day#17]
I went through the training submitted the forms for lab 1 and lab 2 it's been more than 5 working days and I haven't received the digital badge

Is there an issue with the alert ?

Thanks

Best Regards

Georgios Grigoriou

**Comment by hfleitas** [comment]
Hi @Georgios-Grigoriou  did you use the same email address for both labs? @SuryaTejJosyula can look at the received responses, if you can let us know the smtp address you provided.

**Comment by Georgios-Grigoriou** [comment]
Hi @hfleitas and @SuryaTejJosyula , 

thanks for your response.

The e-mail address that I provided  is the following:
georgiosvgrigoriou@gmail.com

**Comment by Georgios-Grigoriou** [comment]
Any update on the above ? Thanks

**Comment by SuryaTejJosyula** [comment]
The badge is issued now to the above email. Thank you for your patience!
